#
# unlock-reopened.yml
# Unlock an issue whenever it is re-opened
#

name: "Unlock reopened issue"

on:
  issues:
    types: [reopened]

jobs:
<<<<<<< HEAD
  lock:
    runs-on: ubuntu-latest
=======
  unlock:
    name: Unlock Reopened
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

>>>>>>> 5513e67512481024e0d571d84487f7c636996803
    steps:
    - uses: OSDKDev/unlock-issues@v1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
